# Generated by Django 2.2.24 on 2021-09-09 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_app', '0002_auto_20210909_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=200)),
                ('long', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('classe', models.CharField(choices=[('A', 'Assistência Social'), ('E', 'Educação'), ('S', 'Saude'), ('EL', 'Esporte e Lazer'), ('P', 'Prédios Públicos'), ('M', 'Meio Ambiente'), ('S', 'Saneamento'), ('C', 'Cultura'), ('O', 'Outros')], max_length=100)),
                ('unidade', models.CharField(max_length=200)),
                ('zone', models.CharField(blank=True, max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Element',
        ),
    ]
